
-- Table: CUSTOMER
CREATE TABLE CUSTOMER (
    CUSTNO int NOT NULL,
    CUSTFIRSTNAME int NULL,
    CUSTLASTNAME int NULL,
    CUSTCITY int NOT NULL,
    CUSTSTATE int NOT NULL,
    CUSTZIP int NOT NULL,
    CUSTBAL int NOT NULL,
    ORDERTBL_EMPNO int NOT NULL,
    CONSTRAINT CUSTOMER_pk PRIMARY KEY (CUSTNO)
);

-- Table: EMPLOYEE
CREATE TABLE EMPLOYEE (
    EMPNO int NOT NULL,
    EMPFIRSTNAME int NULL,
    EMPLASTNAME int NULL,
    EMPPHONE int NOT NULL,
    EMPEMAIL int NULL,
    CONSTRAINT EMPLOYEE_pk PRIMARY KEY (EMPNO)
);

-- Table: ORDERTBL
CREATE TABLE ORDERTBL (
    ORDNO int NOT NULL,
    ORDDATE int NOT NULL,
    CUSTNO int NULL,
    EMPNO int NOT NULL,
    EMPLOYEE_EMPNO int NOT NULL,
    CONSTRAINT ORDERTBL_pk PRIMARY KEY (EMPNO)
);

-- foreign keys
-- Reference: CUSTOMER_ORDERTBL (table: CUSTOMER)
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_ORDERTBL FOREIGN KEY CUSTOMER_ORDERTBL (ORDERTBL_EMPNO)
    REFERENCES ORDERTBL (EMPNO);

-- Reference: ORDERTBL_EMPLOYEE (table: ORDERTBL)
ALTER TABLE ORDERTBL ADD CONSTRAINT ORDERTBL_EMPLOYEE FOREIGN KEY ORDERTBL_EMPLOYEE (EMPLOYEE_EMPNO)
    REFERENCES EMPLOYEE (EMPNO);

-- End of file.

